### ISSUE TITLE
Project Code Cleanup

### ISSUE THREAD

**Issue by epsi1on** [BriefFiniteElementNet/BriefFiniteElement.Net#74]
discussion continued from comment number 673732028 of #36 ([link](https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/issues/36#issuecomment-673732028))

>1. I think having a good coverage is crucial to ensure that people contributing code do not unintentionally break anything. [OpenCover](https://github.com/OpenCover/opencover) reports the following code coverage, which is (expectedly) low:
>        _Line coverage_:  13.4% (2266 of 16832)
>        _Branch coverage_:  13.0% ( 494 of  3788)
> 
Yes i also think that unit tests are not enough yet, online some element helpers have unit tests, others do not. So is it necessary to increase the unit tests?

>2. When building the solution, Visual Studio reports 345 warnings, some of them warning about obsolete code usage, which should easily be fixed, but also many _obsolete_ warnings, telling a feature is incomplete/not working. Such code should not be distributed via nuget (meaning not be part of the main project or master branch).

I've used `[Obsolete()]` attribute for both deprecated codes and new codes which are under development and not tested yet. As you stated, I'm also waiting to get an stable version then publish that version in nuget.org. 

>3. Building the solution with enabled generation of documentation, 1185 warnings are reported. So there's also a massive lack of documentation, which might discourage people to contribute code (because they don't understand the intention of the code that's already there).

You mean XML documentation for methods and fields and property ?

Thanks

**Comment by wo80** [comment]
Regarding point 3: yes, public methods/properties should get xml documentation (at least if the class is public).

I'd suggest to use a task list in you opening post to keep track of the progess. Once we have a plan _what_ to do, we can discuss _how_ to achive this. Feel free to copy the following list to the OP and expand it. Once you've copied it, I'll delete it here:
### Milestone 1
* `BriefFiniteElementNet` / `BriefFiniteElementNet.Common`
   - [ ] Remove obsolete code
   - [ ] Fix not fully implemented classes that use `Obsolete` attribute.
### Milestone 2
* `BriefFiniteElementNet` / `BriefFiniteElementNet.Common`
   - [ ] And unit tests for top-level public classes.
   - [ ] Add XML comments to top-level public classes.
   - [ ] Add XML comments to remaining classes that are frequently used.
### Milestone 3
* `BriefFiniteElementNet` / `BriefFiniteElementNet.Common`
   - [ ] More cleanup ...
* `BriefFiniteElementNet.Validation`
   - [ ] And even more ...

Markdown:
```
### Milestone 1
* `BriefFiniteElementNet` / `BriefFiniteElementNet.Common`
   - [ ] Remove obsolete code
   - [ ] Fix not fully implemented classes that use `Obsolete` attribute.
### Milestone 2
* `BriefFiniteElementNet` / `BriefFiniteElementNet.Common`
   - [ ] And unit tests for top-level public classes.
   - [ ] Add XML comments to top-level public classes.
   - [ ] Add XML comments to remaining classes that are frequently used.
### Milestone 3
* `BriefFiniteElementNet` / `BriefFiniteElementNet.Common`
   - [ ] More cleanup ...
* `BriefFiniteElementNet.Validation`
   - [ ] And even more ...
```

**Comment by wo80** [comment]
You can either remove _Milestone 3_ or add some specific tasks (one addition - with rather low priority - could be to inspect the `TODO`s scattered across the projects).

I think you should put the heading **Plan towards `BriefFiniteElementNet` version 2 and a nuget release** back in place (or change the title of the issue). All the tasks should be addressed **before** publishing a _final_ nuget package. Of course you can publish prerelease packages - as you might have noticed, I added `<Version>2.0.0-pre</Version>` when converting the project files. The `pre` means nuget will handle it as a prerelease.

**Comment by rubsy92** [comment]
Hi, 

I'm going through the todo-list and I noticed item "complete TriangleElement codes that support all 3 types of loads.": [https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/projects/4#card-44141482](link). What do you mean with all 3 types of loads?

**Comment by epsi1on** [comment]
There are 3 type of elemental loads, Uniform, Concentrated and PartialNonUniform. I think currently only uniform load is supported by triangle element.
This method should be implemented for both `DkqHelper` and `CstHelper` that support `ConcentratedLoad` and `PartialNonUniformLoad` : `IElementHelper.GetLocalEquivalentNodalLoads()`
